  name: auto-merge

  on: pull_request

  jobs:
    auto-merge:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: ahmadnassri/action-dependabot-auto-merge@v2
          with:
            github-token: ${{ secrets.DEPENDABOT_TOKEN }}

          
 # automerge:
 #   name: Merge pull request
  #  runs-on: [ubuntu-latest]
   # needs: [build]
   # if: github.base_ref == 'master' && github.actor == 'dependabot[bot]'
   # steps:
   #   - name: Merge
   #     uses: actions/github-script@v3
   #     with:
   #       script: |
   #         github.pullRequests.merge({
   #           owner: context.payload.repository.owner.login,
   #           repo: context.payload.repository.name,
   #           pull_number: context.payload.pull_request.number
   #         })
   #       github-token: ${{secrets.DEPENDABOT_TOKEN}}
