name: Auto Merge Dependency Updates

on:
  - pull_request
  - pull_request_review

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: tjenkinson/gh-action-auto-merge-dependency-updates@v1
        with:
          repo-token: ${{ secrets.DEPENDABOT_TOKEN }}
          allowed-actors: dependabot-preview[bot], dependabot[bot]

          
 # automerge:
 #   name: Merge pull request
  #  runs-on: [ubuntu-latest]
   # needs: [build]
   # if: github.base_ref == 'master' && github.actor == 'dependabot[bot]'
   # steps:
   #   - name: Merge
   #     uses: actions/github-script@v3
   #     with:
   #       script: |
   #         github.pullRequests.merge({
   #           owner: context.payload.repository.owner.login,
   #           repo: context.payload.repository.name,
   #           pull_number: context.payload.pull_request.number
   #         })
   #       github-token: ${{secrets.DEPENDABOT_TOKEN}}
